# Generated by Django 2.2 on 2019-04-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryshow', '0002_auto_20190413_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='director',
            field=models.CharField(default='这里写影片的导演', max_length=100),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=models.CharField(default='在这里写影片的描述', max_length=100),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(default='影片标题', max_length=50),
        ),
    ]
